### ISSUE TITLE
when any category is selected then it returns No News Found

### ISSUE THREAD

**Issue by BlueYeti1881** [gsujanth/NewsReader#1]
when i copy and paste url https://newsapi.org/v2/top-headlines?country=us&apiKey=bbee98d8505449b6ae2f0f5e4bdb22b3&category= in browser then, it gives me with plenty of news in json format but when I launch app  with above url embedded it returns me no news found please help.

**Comment by gsujanth** [comment]
That might be due to API call is not returning data. It is got to do with API key.
